version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    restart: unless-stopped
    container_name: student-dss-api
