apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-dss-data-pvc
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods need to access the same data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-dss-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
